"use client"

import Link from "next/link"
import { useEffect, useState } from "react"
import { usePathname } from "next/navigation"

const STORAGE_KEY = "hideDocsDisclaimerBanner"

export default function DisclaimerBanner() {
  const pathname = usePathname()
  const [isVisible, setIsVisible] = useState<boolean | null>(null)

  useEffect(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY)
      setIsVisible(stored !== "1")
    } catch {
      setIsVisible(true)
    }
  }, [])

  if (!pathname.startsWith("/docs")) return null
  if (pathname === "/docs/disclaimer") return null
  if (isVisible === null || isVisible === false) return null

  const handleClose: React.MouseEventHandler<HTMLButtonElement> = (e) => {
    e.preventDefault()
    e.stopPropagation()
    try {
      localStorage.setItem(STORAGE_KEY, "1")
    } catch {}
    setIsVisible(false)
  }

  return (
    <div className="mt-6">
      <Link
        href="/docs/disclaimer"
        className="group block rounded-lg border border-amber-300/70 bg-amber-50 px-5 py-4 text-amber-900 shadow-sm transition-colors hover:bg-amber-100 dark:border-amber-600/60 dark:bg-amber-900/20 dark:text-amber-100 dark:hover:bg-amber-900/30"
      >
        <div className="flex items-start justify-between gap-3">
          <div className="flex items-center gap-3">
            <span className="text-2xl">⚠️</span>
            <div>
              <p className="text-base font-semibold">Read the Disclaimer</p>
              <p className="text-sm opacity-90">
                Pages were initially generated by AI and may contain inaccuracies.
              </p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <span className="hidden text-sm font-medium underline underline-offset-4 sm:inline">
              Learn more →
            </span>
            <button
              type="button"
              aria-label="Dismiss disclaimer banner"
              className="rounded-md p-1.5 text-amber-900/80 transition-colors hover:bg-amber-200/60 hover:text-amber-900 dark:text-amber-100/80 dark:hover:bg-amber-800/60"
              onClick={handleClose}
            >
              ✕
            </button>
          </div>
        </div>
      </Link>
    </div>
  )
}


